# Generated by Django 4.1.1 on 2022-09-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='getLat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reports',
            name='getLng',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
