# Generated by Django 4.1.1 on 2022-09-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reports_getlat_alter_reports_getlng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='getLat',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reports',
            name='getLng',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
