# Generated by Django 4.1 on 2022-09-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_reports_getlat_alter_reports_getlng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
