# Generated by Django 4.1 on 2022-09-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='usuario',
        ),
    ]
