# Generated by Django 4.1 on 2022-09-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_reports_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='getLat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='getLng',
            new_name='lng',
        ),
        migrations.AddField(
            model_name='reports',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
